version: "3.9"

services:
  bookshelf-app:
    depends_on:
      - bookshelf-db
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    build:
      context: ./bookshelf-service
    environment:
      SPRING_DATASOURCE_USERNAME: ${BOOKSHELF_SERVICE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${BOOKSHELF_SERVICE_POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookshelf-db/${BOOKSHELF_SERVICE_POSTGRES_DB}

  bookshelf-db:
    image: 'postgres:13.1-alpine'
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${BOOKSHELF_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BOOKSHELF_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${BOOKSHELF_SERVICE_POSTGRES_DB}